FROM mcr.microsoft.com/dotnet/runtime:6.0 AS base
WORKDIR /ConsoleApp1

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /ConsoleApp1/ConsoleApp1
COPY ["ConsoleApp1.csproj", "ConsoleApp1/"]
RUN dotnet restore "ConsoleApp1/ConsoleApp1.csproj"
COPY . .
RUN dotnet build "ConsoleApp1.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ConsoleApp1.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /ConsoleApp1
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ConsoleApp1.dll"]
